---
galaxy_info:
  author: Olivia Barker
  description: Install and configure podman on AlmaLinux hosts
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: EL
      versions:
        - "9"
        - "10"

dependencies: []
